apiVersion: v1
kind: Service
metadata:
  name: introduction-svc
  namespace: adeola-ns
spec:
  selector:
    app: introduction
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 324256
  type: NodePort